//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_assignment3_final_edition.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_employee()
        {
            this.tbl_vehicle = new HashSet<tbl_vehicle>();
        }
    
        public string employee_status { get; set; }
        public int Id { get; set; }
        public string employeeName { get; set; }
        public int employeeAge { get; set; }
        public Nullable<double> salary { get; set; }
        public Nullable<double> bouns { get; set; }
        public Nullable<double> rate { get; set; }
        public Nullable<double> hoursWorked { get; set; }
    
        public virtual tbl_status tbl_status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_vehicle> tbl_vehicle { get; set; }
    }
}
